// codegen_python.ts — compiles a SNIL Program AST into equivalent, runnable
// Python 3 source. SNIL is its OWN language; Python is merely its first
// compilation target (like C → assembly). The emitted Python, when executed,
// produces output IDENTICAL to the SNIL interpreter (see GRAMMAR.md + EXPECTED.md).
import type {
  Program, Stmt, Expr,
  VarDecl, Assign, Print, Input, If, ForEach, ForRange, While,
  FuncDecl, Return, Try, Import, ListAdd, ListRemove, FileWrite, FileRead, ExprStmt,
  Binary, Unary, Call, Apply, FuncExpr, Index, Member, Ident,
} from './ast';
import { STDLIB } from './stdlib';
import { SnilError } from './errors';
import { tokenize } from './lexer';
import { parse as parseTokens } from './parser';

// ───────────────────────── Runtime prelude ─────────────────────────
// Emitted at the top of every output so Python display matches SNIL EXACTLY:
//  • integers print without ".0"          • booleans → kweli / si_kweli
//  • tupu (None) → "tupu"                  • lists  → [a, b, c]   (SNIL form)
//  • dicts → {jina: Ali, umri: 20}         (SNIL display form, NOT Python repr)
// `_str` is the SNIL stringifier; `_onyesha` is what `onyesha` prints;
// `_jumla` implements SNIL `+` (string-concat if either side is text, else add).
const PRELUDE = `# -*- coding: utf-8 -*-
# Auto-generated by SNIL → Python codegen. Do not edit.
import math as _math

def _str(x):
    if x is None:
        return "tupu"
    if x is True:
        return "kweli"
    if x is False:
        return "si_kweli"
    if isinstance(x, float):
        if x.is_integer():
            return str(int(x))
        return repr(x)
    if isinstance(x, int):
        return str(x)
    if isinstance(x, str):
        return x
    if isinstance(x, list):
        return "[" + ", ".join(_str(i) for i in x) + "]"
    if isinstance(x, dict):
        return "{" + ", ".join(_str(k) + ": " + _str(v) for k, v in x.items()) + "}"
    return str(x)

def _onyesha(x):
    return _str(x)

def _jumla(a, b):
    if isinstance(a, str) or isinstance(b, str):
        return _str(a) + _str(b)
    return a + b

def _gawanya(a, b):
    if b == 0:
        raise ZeroDivisionError("Huwezi kugawanya kwa sifuri.")
    return a / b

def _idadi(x):
    return len(x)

def _jsmod(a, b):
    # JS-style remainder: sign follows the dividend (truncated), matching SNIL %.
    r = abs(a) % abs(b)
    return -r if a < 0 else r

def _round_half_up(x, dp):
    f = 10 ** dp
    r = _math.floor(abs(x) * f + 0.5) / f
    return -r if x < 0 else r

def _clamp(i, n):
    if i < 0: return 0
    if i > n: return n
    return i

def _kweli(x):
    # SNIL truthiness: False / None / 0 / "" / [] are falsy; else truthy.
    if x is False or x is None:
        return False
    if x == 0 and isinstance(x, (int, float)) and not isinstance(x, bool):
        return False
    if x == "" :
        return False
    if isinstance(x, list) and len(x) == 0:
        return False
    return True

# ── Higher-order builtins (ramani / chuja / punguza) — global, no leta ──
def ramani(orodha, f):
    return [f(_x) for _x in orodha]

def chuja(orodha, f):
    return [_x for _x in orodha if _kweli(f(_x))]

def punguza(orodha, f, anza):
    _acc = anza
    for _x in orodha:
        _acc = f(_acc, _x)
    return _acc

# ── Global builtins (no leta): namba, maandishi, mzunguko, kamili ──
def namba(x):
    if isinstance(x, bool):
        raise Exception('Kazi "namba" inahitaji maandishi au namba.')
    if isinstance(x, (int, float)):
        return x
    if isinstance(x, str):
        t = x.strip()
        try:
            v = float(t)
        except ValueError:
            raise Exception('Kazi "namba" haiwezi kugeuza "' + x + '" kuwa namba.')
        if v.is_integer():
            return int(v)
        return v
    raise Exception('Kazi "namba" inahitaji maandishi au namba.')

def _maandishi(x):
    return _str(x)

def mzunguko(x):
    if isinstance(x, bool) or not isinstance(x, (int, float)):
        raise Exception('Kazi "mzunguko" inahitaji namba.')
    # Round half toward +infinity to match SNIL/JS Math.round semantics.
    import math as _m
    return int(_m.floor(x + 0.5))

def kamili(x):
    if isinstance(x, bool) or not isinstance(x, (int, float)):
        raise Exception('Kazi "kamili" inahitaji namba.')
    return abs(x)

# ── SNIL stdlib (leta hisabati / maandishi / muda / faili) ──
class _Hisabati:
    def jumla(self, xs): return sum(xs)
    def wastani(self, xs): return sum(xs) / len(xs)
    def kiwango_cha_juu(self, xs): return max(xs)
    def kiwango_cha_chini(self, xs): return min(xs)
    def mzizi(self, x): return _math.sqrt(x)
    def kipeo(self, base, exp): return base ** exp
    def kipeo_cha_pili(self, x): return x * x
    def salio(self, a, b):
        if b == 0:
            raise Exception('Kazi "salio" haiwezi kugawanya kwa sifuri.')
        return _jsmod(a, b)
    def mviringo(self, x, dp):
        if isinstance(dp, bool) or not isinstance(dp, int):
            raise Exception('Kazi "mviringo" inahitaji namba kamili.')
        if dp < 0:
            raise Exception('Kazi "mviringo" inahitaji idadi ya desimali isiyo hasi.')
        return _round_half_up(x, dp)
    def mviringo_juu(self, x):
        if isinstance(x, bool) or not isinstance(x, (int, float)):
            raise Exception('Kazi "mviringo_juu" inahitaji namba.')
        return _math.ceil(x)
    def mviringo_chini(self, x):
        if isinstance(x, bool) or not isinstance(x, (int, float)):
            raise Exception('Kazi "mviringo_chini" inahitaji namba.')
        return _math.floor(x)
    def thamani_kamili(self, x):
        if isinstance(x, bool) or not isinstance(x, (int, float)):
            raise Exception('Kazi "thamani_kamili" inahitaji namba.')
        return abs(x)
hisabati = _Hisabati()

class _Maandishi:
    def herufi_kubwa(self, s): return s.upper()
    def herufi_ndogo(self, s): return s.lower()
    def unganisha(self, xs, sep=""): return sep.join(_str(i) for i in xs)
    def gawanya(self, s, sep=" "): return s.split(sep)
    def ina(self, s, part): return part in s
    def badilisha(self, s, old, neu): return s.replace(old, neu)
    def ondoa_nafasi(self, s): return s.strip()
    def anza_na(self, s, x): return s.startswith(x)
    def isha_na(self, s, x): return s.endswith(x)
    def pata(self, s, x): return s.find(x)
    def pindua(self, s): return s[::-1]
    def rudia(self, s, n):
        if isinstance(n, bool) or not isinstance(n, int):
            raise Exception('Kazi "rudia" inahitaji namba kamili.')
        if n < 0:
            raise Exception('Kazi "rudia" inahitaji idadi isiyo hasi.')
        return s * n
    def kata(self, s, anza, mwisho):
        if isinstance(anza, bool) or not isinstance(anza, int) or isinstance(mwisho, bool) or not isinstance(mwisho, int):
            raise Exception('Kazi "kata" inahitaji namba kamili.')
        a = _clamp(anza, len(s)); b = _clamp(mwisho, len(s))
        return "" if a >= b else s[a:b]
maandishi = _Maandishi()

class _Orodha:
    def panga(self, xs):
        copy = list(xs)
        all_num = all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in copy)
        all_str = all(isinstance(x, str) for x in copy)
        if not all_num and not all_str:
            raise Exception('Kazi "panga" inahitaji orodha ya namba pekee au maandishi pekee.')
        return sorted(copy)
    def geuza(self, xs): return list(xs)[::-1]
    def ina(self, xs, kitu): return kitu in xs
    def chukua(self, xs, anza, mwisho):
        if isinstance(anza, bool) or not isinstance(anza, int) or isinstance(mwisho, bool) or not isinstance(mwisho, int):
            raise Exception('Kazi "chukua" inahitaji namba kamili.')
        n = len(xs); a = _clamp(anza, n); b = _clamp(mwisho, n)
        return [] if a >= b else list(xs[a:b])
    def fahirisi(self, xs, kitu):
        for i, x in enumerate(xs):
            if x == kitu: return i
        return -1
    def unganisha_mbili(self, a, b):
        if not isinstance(a, list) or not isinstance(b, list):
            raise Exception('Kazi "unganisha_mbili" inahitaji orodha.')
        return list(a) + list(b)
    def kichwa(self, xs):
        if len(xs) == 0:
            raise Exception('Kazi "kichwa" inahitaji orodha isiyo tupu.')
        return xs[0]
    def mkia(self, xs):
        if len(xs) == 0:
            raise Exception('Kazi "mkia" inahitaji orodha isiyo tupu.')
        return list(xs[1:])
orodha = _Orodha()

class _Kamusi:
    def funguo(self, d):
        if not isinstance(d, dict):
            raise Exception('Kazi "funguo" inahitaji kamusi.')
        return list(d.keys())
    def thamani(self, d):
        if not isinstance(d, dict):
            raise Exception('Kazi "thamani" inahitaji kamusi.')
        return list(d.values())
    def ina_ufunguo(self, d, key):
        if not isinstance(d, dict):
            raise Exception('Kazi "ina_ufunguo" inahitaji kamusi.')
        return key in d
    def idadi_funguo(self, d):
        if not isinstance(d, dict):
            raise Exception('Kazi "idadi_funguo" inahitaji kamusi.')
        return len(d)
kamusi = _Kamusi()

# ── SNIL value-equality (mirrors interpreter valuesEqual / JS _eq) ──
def _eq(a, b):
    if a is b:
        return True
    if isinstance(a, bool) or isinstance(b, bool):
        return a is b
    if isinstance(a, list) and isinstance(b, list):
        if len(a) != len(b):
            return False
        return all(_eq(x, y) for x, y in zip(a, b))
    if isinstance(a, dict) and isinstance(b, dict):
        if len(a) != len(b):
            return False
        for k, v in a.items():
            if k not in b or not _eq(v, b[k]):
                return False
        return True
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return a == b
    if isinstance(a, str) and isinstance(b, str):
        return a == b
    if a is None and b is None:
        return True
    return False

# ── JSON (leta json): tengeneza / changanua — compact, byte-identical ──
def _json_escape(s):
    out = ['"']
    for ch in s:
        code = ord(ch)
        if ch == '"': out.append('\\\\"')
        elif ch == "\\\\": out.append("\\\\\\\\")
        elif ch == "\\n": out.append("\\\\n")
        elif ch == "\\r": out.append("\\\\r")
        elif ch == "\\t": out.append("\\\\t")
        elif ch == "\\b": out.append("\\\\b")
        elif ch == "\\f": out.append("\\\\f")
        elif code < 0x20: out.append("\\\\u" + format(code, "04x"))
        else: out.append(ch)
    out.append('"')
    return "".join(out)

def _json_stringify(v):
    if v is None:
        return "null"
    if v is True:
        return "true"
    if v is False:
        return "false"
    if isinstance(v, float):
        import math as _m
        if not _m.isfinite(v):
            raise Exception('Kazi "tengeneza" haiwezi kubadilisha namba isiyo na kikomo kuwa JSON.')
        return _str(v)
    if isinstance(v, int):
        return _str(v)
    if isinstance(v, str):
        return _json_escape(v)
    if isinstance(v, list):
        return "[" + ",".join(_json_stringify(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ",".join(_json_escape(k) + ":" + _json_stringify(val) for k, val in v.items()) + "}"
    raise Exception('Kazi "tengeneza" inahitaji thamani ya JSON (namba, maandishi, kweli, tupu, orodha au kamusi).')

def _json_parse(text):
    state = {"i": 0}
    n = len(text)
    def err():
        raise Exception('Kazi "changanua" imepewa JSON isiyo sahihi.')
    def ws():
        while state["i"] < n and text[state["i"]] in " \\t\\n\\r":
            state["i"] += 1
    def value():
        ws()
        if state["i"] >= n: err()
        c = text[state["i"]]
        if c == "{": return obj()
        if c == "[": return arr()
        if c == '"': return strv()
        if c == "-" or ("0" <= c <= "9"): return num()
        if text.startswith("true", state["i"]): state["i"] += 4; return True
        if text.startswith("false", state["i"]): state["i"] += 5; return False
        if text.startswith("null", state["i"]): state["i"] += 4; return None
        err()
    def obj():
        m = {}
        state["i"] += 1
        ws()
        if state["i"] < n and text[state["i"]] == "}":
            state["i"] += 1; return m
        while True:
            ws()
            if state["i"] >= n or text[state["i"]] != '"': err()
            key = strv()
            ws()
            if state["i"] >= n or text[state["i"]] != ":": err()
            state["i"] += 1
            m[key] = value()
            ws()
            c = text[state["i"]] if state["i"] < n else ""
            if c == ",": state["i"] += 1; continue
            if c == "}": state["i"] += 1; return m
            err()
    def arr():
        a = []
        state["i"] += 1
        ws()
        if state["i"] < n and text[state["i"]] == "]":
            state["i"] += 1; return a
        while True:
            a.append(value())
            ws()
            c = text[state["i"]] if state["i"] < n else ""
            if c == ",": state["i"] += 1; continue
            if c == "]": state["i"] += 1; return a
            err()
    def strv():
        state["i"] += 1
        out = []
        while True:
            if state["i"] >= n: err()
            c = text[state["i"]]; state["i"] += 1
            if c == '"': return "".join(out)
            if c == "\\\\":
                if state["i"] >= n: err()
                e = text[state["i"]]; state["i"] += 1
                if e == '"': out.append('"')
                elif e == "\\\\": out.append("\\\\")
                elif e == "/": out.append("/")
                elif e == "n": out.append("\\n")
                elif e == "t": out.append("\\t")
                elif e == "r": out.append("\\r")
                elif e == "b": out.append("\\b")
                elif e == "f": out.append("\\f")
                elif e == "u":
                    hexs = text[state["i"]:state["i"]+4]
                    if len(hexs) < 4 or any(h not in "0123456789abcdefABCDEF" for h in hexs): err()
                    out.append(chr(int(hexs, 16)))
                    state["i"] += 4
                else: err()
            else:
                out.append(c)
    def num():
        start = state["i"]
        if text[state["i"]] == "-": state["i"] += 1
        while state["i"] < n and "0" <= text[state["i"]] <= "9": state["i"] += 1
        if state["i"] < n and text[state["i"]] == ".":
            state["i"] += 1
            while state["i"] < n and "0" <= text[state["i"]] <= "9": state["i"] += 1
        if state["i"] < n and text[state["i"]] in "eE":
            state["i"] += 1
            if state["i"] < n and text[state["i"]] in "+-": state["i"] += 1
            while state["i"] < n and "0" <= text[state["i"]] <= "9": state["i"] += 1
        slice_ = text[start:state["i"]]
        if slice_ == "" or slice_ == "-": err()
        if "." in slice_ or "e" in slice_ or "E" in slice_:
            return float(slice_)
        return int(slice_)
    result = value()
    ws()
    if state["i"] != n: err()
    return result

class _Json:
    def tengeneza(self, v): return _json_stringify(v)
    def changanua(self, s):
        if not isinstance(s, str):
            raise Exception('Kazi "changanua" inahitaji maandishi.')
        return _json_parse(s)
json = _Json()

# ── seti (leta seti): set operations over lists, stable first-occurrence order ──
def _set_dedupe(xs):
    out = []
    for x in xs:
        if not any(_eq(x, y) for y in out):
            out.append(x)
    return out

class _Seti:
    def tengeneza(self, xs):
        if not isinstance(xs, list): raise Exception('Kazi "tengeneza" inahitaji orodha.')
        return _set_dedupe(xs)
    def muungano(self, a, b):
        if not isinstance(a, list) or not isinstance(b, list): raise Exception('Kazi "muungano" inahitaji orodha.')
        return _set_dedupe(list(a) + list(b))
    def makutano(self, a, b):
        if not isinstance(a, list) or not isinstance(b, list): raise Exception('Kazi "makutano" inahitaji orodha.')
        da = _set_dedupe(a)
        return [x for x in da if any(_eq(x, y) for y in b)]
    def tofauti(self, a, b):
        if not isinstance(a, list) or not isinstance(b, list): raise Exception('Kazi "tofauti" inahitaji orodha.')
        da = _set_dedupe(a)
        return [x for x in da if not any(_eq(x, y) for y in b)]
    def ina(self, s, x):
        if not isinstance(s, list): raise Exception('Kazi "ina" inahitaji orodha.')
        return any(_eq(x, y) for y in s)
    def ukubwa(self, s):
        if not isinstance(s, list): raise Exception('Kazi "ukubwa" inahitaji orodha.')
        return len(_set_dedupe(s))
seti = _Seti()

class _Muda:
    def sasa(self):
        import datetime as _dt; return _dt.datetime.now().isoformat()
    def leo(self):
        import datetime as _dt; return _dt.date.today().isoformat()
    def mwaka(self):
        import datetime as _dt; return _dt.date.today().year
    def mwezi(self):
        import datetime as _dt; return _dt.date.today().month
    def siku(self):
        import datetime as _dt; return _dt.date.today().day
muda = _Muda()

class _Faili:
    def soma(self, path):
        with open(path, "r", encoding="utf-8") as f: return f.read()
    def andika(self, path, data=""):
        with open(path, "w", encoding="utf-8") as f: f.write(_str(data))
        return None
    def ipo(self, path):
        import os as _os; return _os.path.exists(path)
    def futa(self, path):
        import os as _os
        if _os.path.exists(path): _os.remove(path)
        return None
faili = _Faili()
`;

// Identifier names that conflict with Python keywords/builtins are mangled.
const PY_RESERVED = new Set([
  'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break',
  'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally',
  'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal',
  'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield',
  'match', 'case',
]);

function safeName(name: string): string {
  if (PY_RESERVED.has(name)) return name + '_';
  return name;
}

export function generatePython(program: Program, somaModuli?: import('./runtime').ModuleResolver): string {
  const out: string[] = [];

  // Anonymous functions (FuncExpr) can't be a Python `lambda` (multi-statement
  // bodies), so each is HOISTED to a uniquely-named `def` emitted immediately
  // before the statement that uses it, and the expression references that name.
  // Closures over outer variables work because the def is emitted in-place (same
  // scope), so it sees the enclosing locals/globals.
  let lambdaCounter = 0;
  const lambdaName = new Map<FuncExpr, string>();

  function line(text: string, depth: number): void {
    out.push('    '.repeat(depth) + text);
  }

  function block(stmts: Stmt[], depth: number): void {
    if (stmts.length === 0) {
      line('pass', depth);
      return;
    }
    for (const s of stmts) emitStmt(s, depth);
  }

  // Collect every FuncExpr reachable in an expression tree WITHOUT descending
  // into a FuncExpr's own body (those nested lambdas are hoisted when that body's
  // statements are emitted). Returns them in source order.
  function funcExprsIn(e: Expr, acc: FuncExpr[]): void {
    switch (e.kind) {
      case 'FuncExpr': acc.push(e); return; // do NOT recurse into body here
      case 'Binary': funcExprsIn(e.left, acc); funcExprsIn(e.right, acc); return;
      case 'Unary': funcExprsIn(e.operand, acc); return;
      case 'Call': for (const a of e.args) funcExprsIn(a, acc); return;
      case 'Apply': funcExprsIn(e.fn, acc); for (const a of e.args) funcExprsIn(a, acc); return;
      case 'Index': funcExprsIn(e.target, acc); funcExprsIn(e.index, acc); return;
      case 'Member': funcExprsIn(e.target, acc); return;
      case 'ListLit': for (const it of e.items) funcExprsIn(it, acc); return;
      case 'DictLit': for (const en of e.entries) funcExprsIn(en.value, acc); return;
      case 'TemplateString':
        for (const p of e.parts) if (p.t === 'expr') funcExprsIn(p.expr, acc);
        return;
      default: return;
    }
  }

  // Every expression a statement evaluates DIRECTLY (not via a child block).
  function stmtExprs(s: Stmt): Expr[] {
    switch (s.kind) {
      case 'VarDecl': return [s.value];
      case 'Assign': return [...lvalueExprs(s.target), s.value];
      case 'Print': return [s.value];
      case 'Input': return [s.prompt];
      case 'If': return [s.cond];
      case 'ForEach': return [s.iterable];
      case 'ForRange': return [s.from, s.to];
      case 'While': return [s.cond];
      case 'Return': return s.value ? [s.value] : [];
      case 'ListAdd': return [s.item, s.list];
      case 'ListRemove': return [s.item, s.list];
      case 'FileWrite': return [s.data, s.path];
      case 'FileRead': return [s.path];
      case 'ExprStmt': return [s.expr];
      default: return [];
    }
  }

  function lvalueExprs(target: Ident | Index | Member): Expr[] {
    if (target.kind === 'Index') return [target.target, target.index];
    if (target.kind === 'Member') return [target.target];
    return [];
  }

  // Emit `def`s for FuncExprs used directly by this statement, in source order.
  function hoistLambdas(s: Stmt, depth: number): void {
    const found: FuncExpr[] = [];
    for (const e of stmtExprs(s)) funcExprsIn(e, found);
    for (const fx of found) {
      if (lambdaName.has(fx)) continue;
      const name = `_kazi_${lambdaCounter++}`;
      lambdaName.set(fx, name);
      const params = fx.params.map(safeName).join(', ');
      line(`def ${name}(${params}):`, depth);
      block(fx.body, depth + 1);
    }
  }

  function emitStmt(s: Stmt, depth: number): void {
    hoistLambdas(s, depth);
    switch (s.kind) {
      case 'VarDecl': {
        const n = s as VarDecl;
        line(`${safeName(n.name)} = ${expr(n.value)}`, depth);
        return;
      }
      case 'Assign': {
        const n = s as Assign;
        line(`${lvalue(n.target)} = ${expr(n.value)}`, depth);
        return;
      }
      case 'Print': {
        const n = s as Print;
        line(`print(_onyesha(${expr(n.value)}))`, depth);
        return;
      }
      case 'Input': {
        const n = s as Input;
        line(`${safeName(n.name)} = input(_str(${expr(n.prompt)}))`, depth);
        return;
      }
      case 'If': {
        const n = s as If;
        line(`if ${expr(n.cond)}:`, depth);
        block(n.then, depth + 1);
        if (n.otherwise !== null) {
          line('else:', depth);
          block(n.otherwise, depth + 1);
        }
        return;
      }
      case 'ForEach': {
        const n = s as ForEach;
        line(`for ${safeName(n.varName)} in ${expr(n.iterable)}:`, depth);
        block(n.body, depth + 1);
        return;
      }
      case 'ForRange': {
        const n = s as ForRange;
        // a..b INCLUSIVE both ends
        line(`for ${safeName(n.varName)} in range(${expr(n.from)}, (${expr(n.to)}) + 1):`, depth);
        block(n.body, depth + 1);
        return;
      }
      case 'While': {
        const n = s as While;
        line(`while ${expr(n.cond)}:`, depth);
        block(n.body, depth + 1);
        return;
      }
      case 'FuncDecl': {
        const n = s as FuncDecl;
        const params = n.params.map(safeName).join(', ');
        line(`def ${safeName(n.name)}(${params}):`, depth);
        block(n.body, depth + 1);
        return;
      }
      case 'Return': {
        const n = s as Return;
        line(n.value === null ? 'return' : `return ${expr(n.value)}`, depth);
        return;
      }
      case 'Try': {
        const n = s as Try;
        line('try:', depth);
        block(n.body, depth + 1);
        line('except Exception:', depth);
        block(n.handler, depth + 1);
        return;
      }
      case 'Import': {
        const n = s as Import;
        if (n.isFile) {
          // File module: its compiled statements are inlined ONCE at top level
          // (see gatherFileModules below), so the import site itself emits nothing.
          // Bare names (kazi/weka) are already global Python names by this point.
          line(`# leta "${n.module}"`, depth);
          return;
        }
        // `leta X` flattens the stdlib module's functions into bare names — matching
        // the interpreter (so `jumla(...)` works after `leta hisabati`). Module
        // objects live in the prelude.
        const mod = STDLIB[n.module];
        if (mod) {
          for (const fn of Object.keys(mod)) line(`${safeName(fn)} = ${n.module}.${fn}`, depth);
        } else {
          line(`# leta ${n.module}`, depth);
        }
        return;
      }
      case 'ListAdd': {
        const n = s as ListAdd;
        line(`(${expr(n.list)}).append(${expr(n.item)})`, depth);
        return;
      }
      case 'ListRemove': {
        const n = s as ListRemove;
        line(`(${expr(n.list)}).remove(${expr(n.item)})`, depth);
        return;
      }
      case 'FileWrite': {
        const n = s as FileWrite;
        line(`with open(${expr(n.path)}, "w", encoding="utf-8") as _f:`, depth);
        line(`_f.write(_str(${expr(n.data)}))`, depth + 1);
        return;
      }
      case 'FileRead': {
        const n = s as FileRead;
        line(`with open(${expr(n.path)}, "r", encoding="utf-8") as _f:`, depth);
        line(`${safeName(n.name)} = _f.read()`, depth + 1);
        return;
      }
      case 'ExprStmt': {
        const n = s as ExprStmt;
        line(expr(n.expr), depth);
        return;
      }
      default: {
        const _exhaustive: never = s;
        throw new Error(`SNIL codegen: aina ya sentensi haijatekelezwa: ${(_exhaustive as Stmt).kind}`);
      }
    }
  }

  function lvalue(target: Ident | Index | Member): string {
    switch (target.kind) {
      case 'Ident':
        return safeName(target.name);
      case 'Index':
        return `${expr(target.target)}[${expr(target.index)}]`;
      case 'Member':
        // SNIL dicts compile to Python dicts → member access is subscript.
        return `${expr(target.target)}[${str(target.name)}]`;
    }
  }

  function str(s: string): string {
    return JSON.stringify(s);
  }

  function expr(e: Expr): string {
    switch (e.kind) {
      case 'NumberLit': {
        // Integers stay int (so they print without ".0"); decimals stay float.
        const v = e.value;
        return Number.isInteger(v) ? String(v) : String(v);
      }
      case 'StringLit':
        return str(e.value);
      case 'TemplateString': {
        // "Habari {jina}!" → ("Habari " + _str(jina) + "!"). Literal parts stay
        // plain strings; expr parts go through _str (same stringify as SNIL `+`).
        const pieces = e.parts.map((p) =>
          p.t === 'lit' ? str(p.value) : `_str(${expr(p.expr)})`,
        );
        return pieces.length ? `(${pieces.join(' + ')})` : '""';
      }
      case 'BoolLit':
        return e.value ? 'True' : 'False';
      case 'NullLit':
        return 'None';
      case 'ListLit':
        return `[${e.items.map(expr).join(', ')}]`;
      case 'DictLit':
        return `{${e.entries.map((en) => `${str(en.key)}: ${expr(en.value)}`).join(', ')}}`;
      case 'Ident':
        return safeName(e.name);
      case 'Binary':
        return binary(e as Binary);
      case 'Unary':
        return unary(e as Unary);
      case 'Call':
        return call(e as Call);
      case 'Apply': {
        const a = e as Apply;
        const args = a.args.map(expr).join(', ');
        return `(${expr(a.fn)})(${args})`;
      }
      case 'FuncExpr': {
        // Reference the hoisted def emitted by hoistLambdas before this statement.
        const name = lambdaName.get(e as FuncExpr);
        if (!name) throw new Error('SNIL codegen: FuncExpr haijapandishwa (hoist) kabla ya matumizi.');
        return name;
      }
      case 'Index':
        return `${expr((e as Index).target)}[${expr((e as Index).index)}]`;
      case 'Member':
        return `${expr((e as Member).target)}[${str((e as Member).name)}]`;
      default: {
        const _exhaustive: never = e;
        throw new Error(`SNIL codegen: aina ya msemo haijatekelezwa: ${(_exhaustive as Expr).kind}`);
      }
    }
  }

  function binary(e: Binary): string {
    const l = expr(e.left);
    const r = expr(e.right);
    switch (e.op) {
      case '+':
        // SNIL `+`: string-concat if either side is text, else numeric add.
        return `_jumla(${l}, ${r})`;
      case '-': return `(${l} - ${r})`;
      case '*': return `(${l} * ${r})`;
      case '/': return `_gawanya(${l}, ${r})`;
      case '%': return `(${l} % ${r})`;
      case '==': return `(${l} == ${r})`;
      case '!=': return `(${l} != ${r})`;
      case '<': return `(${l} < ${r})`;
      case '>': return `(${l} > ${r})`;
      case '<=': return `(${l} <= ${r})`;
      case '>=': return `(${l} >= ${r})`;
      case 'na': return `(${l} and ${r})`;
      case 'au': return `(${l} or ${r})`;
    }
  }

  function unary(e: Unary): string {
    const v = expr(e.operand);
    if (e.op === 'sio') return `(not ${v})`;
    return `(-${v})`;
  }

  function call(e: Call): string {
    const args = e.args.map(expr).join(', ');
    // Global builtins available without `leta`.
    if (e.callee === 'idadi') return `_idadi(${args})`;
    // `maandishi` is BOTH a global builtin and a module name; the module instance
    // (maandishi = _Maandishi()) would shadow the builtin, so route the global
    // display-string builtin to its underscored prelude function (like _idadi).
    if (e.callee === 'maandishi') return `_maandishi(${args})`;
    return `${safeName(e.callee)}(${args})`;
  }

  // ── gather transitively-imported file modules ──
  // DFS from main, DEDUPED by module name, CYCLE-SAFE (don't recurse into a module
  // that is already on the visiting stack), emitted in dependency order
  // (imported-before-importer). Each module body is compiled exactly ONCE so its
  // top-level kazi/weka become global Python names — exactly the bare-name exposure
  // the interpreter produces.
  function fileImportsOf(body: Stmt[]): Import[] {
    const found: Import[] = [];
    for (const s of body) {
      if (s.kind === 'Import' && (s as Import).isFile) found.push(s as Import);
    }
    return found;
  }

  const moduleOrder: { name: string; body: Stmt[] }[] = [];
  const emitted = new Set<string>();   // dedup: a module is inlined at most once
  const visiting = new Set<string>();  // cycle guard: modules on the current DFS path

  function visitModule(imp: Import): void {
    const name = imp.module;
    if (emitted.has(name)) return;     // already inlined elsewhere
    if (visiting.has(name)) return;    // cycle — already being processed up-stack
    if (!somaModuli) {
      throw new SnilError(
        `Moduli "${name}" haijapatikana.`, imp.line, 'kutekeleza',
        'mazingira haya hayana kisuluhishi cha moduli (somaModuli)',
      );
    }
    const source = somaModuli(name);
    if (source == null) {
      throw new SnilError(`Moduli "${name}" haijapatikana.`, imp.line, 'kutekeleza');
    }
    const modProgram = parseTokens(tokenize(source));
    visiting.add(name);
    // Dependencies first (so imported modules are inlined before this one).
    for (const dep of fileImportsOf(modProgram.body)) visitModule(dep);
    visiting.delete(name);
    if (!emitted.has(name)) {
      emitted.add(name);
      moduleOrder.push({ name, body: modProgram.body });
    }
  }

  for (const imp of fileImportsOf(program.body)) visitModule(imp);

  // ── assemble ──
  // 1) inlined file-modules (dependency order), each emitted ONCE at top level.
  for (const mod of moduleOrder) {
    out.push(`# ── moduli "${mod.name}" (imeingizwa moja kwa moja) ──`);
    for (const s of mod.body) emitStmt(s, 0);
  }
  // 2) the main program body.
  for (const s of program.body) emitStmt(s, 0);

  return PRELUDE + '\n' + (out.length ? out.join('\n') + '\n' : '');
}
