// codegen_python.ts — compiles a SNIL Program AST into equivalent, runnable
// Python 3 source. SNIL is its OWN language; Python is merely its first
// compilation target (like C → assembly). The emitted Python, when executed,
// produces output IDENTICAL to the SNIL interpreter (see GRAMMAR.md + EXPECTED.md).
import type {
  Program, Stmt, Expr,
  VarDecl, Assign, Print, Input, If, ForEach, ForRange, While,
  FuncDecl, Return, Try, Import, ListAdd, ListRemove, FileWrite, FileRead, ExprStmt,
  Binary, Unary, Call, Index, Member, Ident,
} from './ast';
import { STDLIB } from './stdlib';
import { SnilError } from './errors';
import { tokenize } from './lexer';
import { parse as parseTokens } from './parser';

// ───────────────────────── Runtime prelude ─────────────────────────
// Emitted at the top of every output so Python display matches SNIL EXACTLY:
//  • integers print without ".0"          • booleans → kweli / si_kweli
//  • tupu (None) → "tupu"                  • lists  → [a, b, c]   (SNIL form)
//  • dicts → {jina: Ali, umri: 20}         (SNIL display form, NOT Python repr)
// `_str` is the SNIL stringifier; `_onyesha` is what `onyesha` prints;
// `_jumla` implements SNIL `+` (string-concat if either side is text, else add).
const PRELUDE = `# -*- coding: utf-8 -*-
# Auto-generated by SNIL → Python codegen. Do not edit.
import math as _math

def _str(x):
    if x is None:
        return "tupu"
    if x is True:
        return "kweli"
    if x is False:
        return "si_kweli"
    if isinstance(x, float):
        if x.is_integer():
            return str(int(x))
        return repr(x)
    if isinstance(x, int):
        return str(x)
    if isinstance(x, str):
        return x
    if isinstance(x, list):
        return "[" + ", ".join(_str(i) for i in x) + "]"
    if isinstance(x, dict):
        return "{" + ", ".join(_str(k) + ": " + _str(v) for k, v in x.items()) + "}"
    return str(x)

def _onyesha(x):
    return _str(x)

def _jumla(a, b):
    if isinstance(a, str) or isinstance(b, str):
        return _str(a) + _str(b)
    return a + b

def _gawanya(a, b):
    if b == 0:
        raise ZeroDivisionError("Huwezi kugawanya kwa sifuri.")
    return a / b

def _idadi(x):
    return len(x)

# ── Global builtins (no leta): namba, maandishi, mzunguko, kamili ──
def namba(x):
    if isinstance(x, bool):
        raise Exception('Kazi "namba" inahitaji maandishi au namba.')
    if isinstance(x, (int, float)):
        return x
    if isinstance(x, str):
        t = x.strip()
        try:
            v = float(t)
        except ValueError:
            raise Exception('Kazi "namba" haiwezi kugeuza "' + x + '" kuwa namba.')
        if v.is_integer():
            return int(v)
        return v
    raise Exception('Kazi "namba" inahitaji maandishi au namba.')

def _maandishi(x):
    return _str(x)

def mzunguko(x):
    if isinstance(x, bool) or not isinstance(x, (int, float)):
        raise Exception('Kazi "mzunguko" inahitaji namba.')
    # Round half toward +infinity to match SNIL/JS Math.round semantics.
    import math as _m
    return int(_m.floor(x + 0.5))

def kamili(x):
    if isinstance(x, bool) or not isinstance(x, (int, float)):
        raise Exception('Kazi "kamili" inahitaji namba.')
    return abs(x)

# ── SNIL stdlib (leta hisabati / maandishi / muda / faili) ──
class _Hisabati:
    def jumla(self, xs): return sum(xs)
    def wastani(self, xs): return sum(xs) / len(xs)
    def kiwango_cha_juu(self, xs): return max(xs)
    def kiwango_cha_chini(self, xs): return min(xs)
    def mzizi(self, x): return _math.sqrt(x)
    def kipeo(self, base, exp): return base ** exp
hisabati = _Hisabati()

class _Maandishi:
    def herufi_kubwa(self, s): return s.upper()
    def herufi_ndogo(self, s): return s.lower()
    def unganisha(self, xs, sep=""): return sep.join(_str(i) for i in xs)
    def gawanya(self, s, sep=" "): return s.split(sep)
    def ina(self, s, part): return part in s
    def badilisha(self, s, old, neu): return s.replace(old, neu)
    def ondoa_nafasi(self, s): return s.strip()
maandishi = _Maandishi()

class _Orodha:
    def panga(self, xs):
        copy = list(xs)
        all_num = all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in copy)
        all_str = all(isinstance(x, str) for x in copy)
        if not all_num and not all_str:
            raise Exception('Kazi "panga" inahitaji orodha ya namba pekee au maandishi pekee.')
        return sorted(copy)
    def geuza(self, xs): return list(xs)[::-1]
    def ina(self, xs, kitu): return kitu in xs
orodha = _Orodha()

class _Muda:
    def sasa(self):
        import datetime as _dt; return _dt.datetime.now().isoformat()
    def leo(self):
        import datetime as _dt; return _dt.date.today().isoformat()
    def mwaka(self):
        import datetime as _dt; return _dt.date.today().year
    def mwezi(self):
        import datetime as _dt; return _dt.date.today().month
    def siku(self):
        import datetime as _dt; return _dt.date.today().day
muda = _Muda()

class _Faili:
    def soma(self, path):
        with open(path, "r", encoding="utf-8") as f: return f.read()
    def andika(self, path, data=""):
        with open(path, "w", encoding="utf-8") as f: f.write(_str(data))
        return None
    def ipo(self, path):
        import os as _os; return _os.path.exists(path)
    def futa(self, path):
        import os as _os
        if _os.path.exists(path): _os.remove(path)
        return None
faili = _Faili()
`;

// Identifier names that conflict with Python keywords/builtins are mangled.
const PY_RESERVED = new Set([
  'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break',
  'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally',
  'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal',
  'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield',
  'match', 'case',
]);

function safeName(name: string): string {
  if (PY_RESERVED.has(name)) return name + '_';
  return name;
}

export function generatePython(program: Program, somaModuli?: import('./runtime').ModuleResolver): string {
  const out: string[] = [];

  function line(text: string, depth: number): void {
    out.push('    '.repeat(depth) + text);
  }

  function block(stmts: Stmt[], depth: number): void {
    if (stmts.length === 0) {
      line('pass', depth);
      return;
    }
    for (const s of stmts) emitStmt(s, depth);
  }

  function emitStmt(s: Stmt, depth: number): void {
    switch (s.kind) {
      case 'VarDecl': {
        const n = s as VarDecl;
        line(`${safeName(n.name)} = ${expr(n.value)}`, depth);
        return;
      }
      case 'Assign': {
        const n = s as Assign;
        line(`${lvalue(n.target)} = ${expr(n.value)}`, depth);
        return;
      }
      case 'Print': {
        const n = s as Print;
        line(`print(_onyesha(${expr(n.value)}))`, depth);
        return;
      }
      case 'Input': {
        const n = s as Input;
        line(`${safeName(n.name)} = input(_str(${expr(n.prompt)}))`, depth);
        return;
      }
      case 'If': {
        const n = s as If;
        line(`if ${expr(n.cond)}:`, depth);
        block(n.then, depth + 1);
        if (n.otherwise !== null) {
          line('else:', depth);
          block(n.otherwise, depth + 1);
        }
        return;
      }
      case 'ForEach': {
        const n = s as ForEach;
        line(`for ${safeName(n.varName)} in ${expr(n.iterable)}:`, depth);
        block(n.body, depth + 1);
        return;
      }
      case 'ForRange': {
        const n = s as ForRange;
        // a..b INCLUSIVE both ends
        line(`for ${safeName(n.varName)} in range(${expr(n.from)}, (${expr(n.to)}) + 1):`, depth);
        block(n.body, depth + 1);
        return;
      }
      case 'While': {
        const n = s as While;
        line(`while ${expr(n.cond)}:`, depth);
        block(n.body, depth + 1);
        return;
      }
      case 'FuncDecl': {
        const n = s as FuncDecl;
        const params = n.params.map(safeName).join(', ');
        line(`def ${safeName(n.name)}(${params}):`, depth);
        block(n.body, depth + 1);
        return;
      }
      case 'Return': {
        const n = s as Return;
        line(n.value === null ? 'return' : `return ${expr(n.value)}`, depth);
        return;
      }
      case 'Try': {
        const n = s as Try;
        line('try:', depth);
        block(n.body, depth + 1);
        line('except Exception:', depth);
        block(n.handler, depth + 1);
        return;
      }
      case 'Import': {
        const n = s as Import;
        if (n.isFile) {
          // File module: its compiled statements are inlined ONCE at top level
          // (see gatherFileModules below), so the import site itself emits nothing.
          // Bare names (kazi/weka) are already global Python names by this point.
          line(`# leta "${n.module}"`, depth);
          return;
        }
        // `leta X` flattens the stdlib module's functions into bare names — matching
        // the interpreter (so `jumla(...)` works after `leta hisabati`). Module
        // objects live in the prelude.
        const mod = STDLIB[n.module];
        if (mod) {
          for (const fn of Object.keys(mod)) line(`${safeName(fn)} = ${n.module}.${fn}`, depth);
        } else {
          line(`# leta ${n.module}`, depth);
        }
        return;
      }
      case 'ListAdd': {
        const n = s as ListAdd;
        line(`(${expr(n.list)}).append(${expr(n.item)})`, depth);
        return;
      }
      case 'ListRemove': {
        const n = s as ListRemove;
        line(`(${expr(n.list)}).remove(${expr(n.item)})`, depth);
        return;
      }
      case 'FileWrite': {
        const n = s as FileWrite;
        line(`with open(${expr(n.path)}, "w", encoding="utf-8") as _f:`, depth);
        line(`_f.write(_str(${expr(n.data)}))`, depth + 1);
        return;
      }
      case 'FileRead': {
        const n = s as FileRead;
        line(`with open(${expr(n.path)}, "r", encoding="utf-8") as _f:`, depth);
        line(`${safeName(n.name)} = _f.read()`, depth + 1);
        return;
      }
      case 'ExprStmt': {
        const n = s as ExprStmt;
        line(expr(n.expr), depth);
        return;
      }
      default: {
        const _exhaustive: never = s;
        throw new Error(`SNIL codegen: aina ya sentensi haijatekelezwa: ${(_exhaustive as Stmt).kind}`);
      }
    }
  }

  function lvalue(target: Ident | Index | Member): string {
    switch (target.kind) {
      case 'Ident':
        return safeName(target.name);
      case 'Index':
        return `${expr(target.target)}[${expr(target.index)}]`;
      case 'Member':
        // SNIL dicts compile to Python dicts → member access is subscript.
        return `${expr(target.target)}[${str(target.name)}]`;
    }
  }

  function str(s: string): string {
    return JSON.stringify(s);
  }

  function expr(e: Expr): string {
    switch (e.kind) {
      case 'NumberLit': {
        // Integers stay int (so they print without ".0"); decimals stay float.
        const v = e.value;
        return Number.isInteger(v) ? String(v) : String(v);
      }
      case 'StringLit':
        return str(e.value);
      case 'TemplateString': {
        // "Habari {jina}!" → ("Habari " + _str(jina) + "!"). Literal parts stay
        // plain strings; expr parts go through _str (same stringify as SNIL `+`).
        const pieces = e.parts.map((p) =>
          p.t === 'lit' ? str(p.value) : `_str(${expr(p.expr)})`,
        );
        return pieces.length ? `(${pieces.join(' + ')})` : '""';
      }
      case 'BoolLit':
        return e.value ? 'True' : 'False';
      case 'NullLit':
        return 'None';
      case 'ListLit':
        return `[${e.items.map(expr).join(', ')}]`;
      case 'DictLit':
        return `{${e.entries.map((en) => `${str(en.key)}: ${expr(en.value)}`).join(', ')}}`;
      case 'Ident':
        return safeName(e.name);
      case 'Binary':
        return binary(e as Binary);
      case 'Unary':
        return unary(e as Unary);
      case 'Call':
        return call(e as Call);
      case 'Index':
        return `${expr((e as Index).target)}[${expr((e as Index).index)}]`;
      case 'Member':
        return `${expr((e as Member).target)}[${str((e as Member).name)}]`;
      default: {
        const _exhaustive: never = e;
        throw new Error(`SNIL codegen: aina ya msemo haijatekelezwa: ${(_exhaustive as Expr).kind}`);
      }
    }
  }

  function binary(e: Binary): string {
    const l = expr(e.left);
    const r = expr(e.right);
    switch (e.op) {
      case '+':
        // SNIL `+`: string-concat if either side is text, else numeric add.
        return `_jumla(${l}, ${r})`;
      case '-': return `(${l} - ${r})`;
      case '*': return `(${l} * ${r})`;
      case '/': return `_gawanya(${l}, ${r})`;
      case '%': return `(${l} % ${r})`;
      case '==': return `(${l} == ${r})`;
      case '!=': return `(${l} != ${r})`;
      case '<': return `(${l} < ${r})`;
      case '>': return `(${l} > ${r})`;
      case '<=': return `(${l} <= ${r})`;
      case '>=': return `(${l} >= ${r})`;
      case 'na': return `(${l} and ${r})`;
      case 'au': return `(${l} or ${r})`;
    }
  }

  function unary(e: Unary): string {
    const v = expr(e.operand);
    if (e.op === 'sio') return `(not ${v})`;
    return `(-${v})`;
  }

  function call(e: Call): string {
    const args = e.args.map(expr).join(', ');
    // Global builtins available without `leta`.
    if (e.callee === 'idadi') return `_idadi(${args})`;
    // `maandishi` is BOTH a global builtin and a module name; the module instance
    // (maandishi = _Maandishi()) would shadow the builtin, so route the global
    // display-string builtin to its underscored prelude function (like _idadi).
    if (e.callee === 'maandishi') return `_maandishi(${args})`;
    return `${safeName(e.callee)}(${args})`;
  }

  // ── gather transitively-imported file modules ──
  // DFS from main, DEDUPED by module name, CYCLE-SAFE (don't recurse into a module
  // that is already on the visiting stack), emitted in dependency order
  // (imported-before-importer). Each module body is compiled exactly ONCE so its
  // top-level kazi/weka become global Python names — exactly the bare-name exposure
  // the interpreter produces.
  function fileImportsOf(body: Stmt[]): Import[] {
    const found: Import[] = [];
    for (const s of body) {
      if (s.kind === 'Import' && (s as Import).isFile) found.push(s as Import);
    }
    return found;
  }

  const moduleOrder: { name: string; body: Stmt[] }[] = [];
  const emitted = new Set<string>();   // dedup: a module is inlined at most once
  const visiting = new Set<string>();  // cycle guard: modules on the current DFS path

  function visitModule(imp: Import): void {
    const name = imp.module;
    if (emitted.has(name)) return;     // already inlined elsewhere
    if (visiting.has(name)) return;    // cycle — already being processed up-stack
    if (!somaModuli) {
      throw new SnilError(
        `Moduli "${name}" haijapatikana.`, imp.line, 'kutekeleza',
        'mazingira haya hayana kisuluhishi cha moduli (somaModuli)',
      );
    }
    const source = somaModuli(name);
    if (source == null) {
      throw new SnilError(`Moduli "${name}" haijapatikana.`, imp.line, 'kutekeleza');
    }
    const modProgram = parseTokens(tokenize(source));
    visiting.add(name);
    // Dependencies first (so imported modules are inlined before this one).
    for (const dep of fileImportsOf(modProgram.body)) visitModule(dep);
    visiting.delete(name);
    if (!emitted.has(name)) {
      emitted.add(name);
      moduleOrder.push({ name, body: modProgram.body });
    }
  }

  for (const imp of fileImportsOf(program.body)) visitModule(imp);

  // ── assemble ──
  // 1) inlined file-modules (dependency order), each emitted ONCE at top level.
  for (const mod of moduleOrder) {
    out.push(`# ── moduli "${mod.name}" (imeingizwa moja kwa moja) ──`);
    for (const s of mod.body) emitStmt(s, 0);
  }
  // 2) the main program body.
  for (const s of program.body) emitStmt(s, 0);

  return PRELUDE + '\n' + (out.length ? out.join('\n') + '\n' : '');
}
