// codegen_js.ts — compiles a SNIL Program AST into equivalent, runnable
// JavaScript (ES2020, runnable via `node`). SNIL is its OWN language; JavaScript
// is a second compilation target alongside Python. The emitted JS, when executed,
// produces output IDENTICAL to the SNIL interpreter and the Python backend
// (see GRAMMAR.md + EXPECTED.md).
//
// This file MIRRORS codegen_python.ts in structure and quality:
//  • a runtime PRELUDE that replicates SNIL display + arithmetic + stdlib
//  • `leta hisabati`/etc → flatten stdlib module functions to bare names
//  • `leta "x"` file imports → INLINE the module's compiled code once
//    (dependency-ordered, deduped, cycle-safe) using the ModuleResolver
import type {
  Program, Stmt, Expr,
  VarDecl, Assign, Print, Input, If, ForEach, ForRange, While,
  FuncDecl, Return, Try, Import, ListAdd, ListRemove, FileWrite, FileRead, ExprStmt,
  Binary, Unary, Call, Index, Member, Ident,
} from './ast';
import { STDLIB } from './stdlib';
import { SnilError } from './errors';
import { tokenize } from './lexer';
import { parse as parseTokens } from './parser';

// ───────────────────────── Runtime prelude ─────────────────────────
// Emitted at the top of every output so JS display matches SNIL EXACTLY:
//  • integer-valued numbers print without ".0"   • booleans → kweli / si_kweli
//  • tupu (null) → "tupu"                         • lists  → [a, b, c] (SNIL form)
//  • dicts/objects → {jina: Ali, umri: 20}        (SNIL display form, NOT JSON)
//
// Helpers:
//  • _str     — SNIL stringifier (display form)
//  • _onyesha — what `onyesha` prints (collects output, flushed at end)
//  • _jumla   — SNIL `+` (string-concat if either side is text, else numeric add)
//  • _gawanya — division (÷0 → Kiswahili Error)
//  • _idadi   — length
//  • _kweli   — SNIL truthiness (false/null/0/""/[] are falsy; note: [] is
//               truthy in plain JS, so every ikiwa/wakati/na/au/sio condition is
//               wrapped in _kweli to replicate SNIL semantics)
//  • _eq      — SNIL equality (deep for lists/objects)
//  • global builtins: namba / _maandishi / mzunguko / kamili / idadi
//  • SNIL stdlib objects: hisabati / maandishi / orodha / muda / faili
const PRELUDE = `// Auto-generated by SNIL → JavaScript codegen. Do not edit.
"use strict";
const _out = [];

function _str(x) {
  if (x === null || x === undefined) return "tupu";
  if (x === true) return "kweli";
  if (x === false) return "si_kweli";
  if (typeof x === "number") {
    if (Number.isInteger(x)) return String(x);
    return String(x);
  }
  if (typeof x === "string") return x;
  if (Array.isArray(x)) return "[" + x.map(_str).join(", ") + "]";
  if (typeof x === "object") {
    return "{" + Object.keys(x).map((k) => _str(k) + ": " + _str(x[k])).join(", ") + "}";
  }
  return String(x);
}

function _onyesha(x) { _out.push(_str(x)); }

function _kweli(x) {
  if (x === false || x === null || x === undefined) return false;
  if (x === 0) return false;
  if (x === "") return false;
  if (Array.isArray(x) && x.length === 0) return false;
  return true;
}

function _eq(a, b) {
  if (a === b) return true;
  if (Array.isArray(a) && Array.isArray(b)) {
    if (a.length !== b.length) return false;
    return a.every((x, i) => _eq(x, b[i]));
  }
  if (a && b && typeof a === "object" && typeof b === "object" && !Array.isArray(a) && !Array.isArray(b)) {
    const ka = Object.keys(a), kb = Object.keys(b);
    if (ka.length !== kb.length) return false;
    return ka.every((k) => Object.prototype.hasOwnProperty.call(b, k) && _eq(a[k], b[k]));
  }
  return false;
}

function _jumla(a, b) {
  if (typeof a === "string" || typeof b === "string") return _str(a) + _str(b);
  return a + b;
}

function _gawanya(a, b) {
  if (b === 0) throw new Error("Huwezi kugawanya kwa sifuri.");
  return a / b;
}

function _idadi(x) {
  if (Array.isArray(x) || typeof x === "string") return x.length;
  throw new Error('Kazi "idadi" inahitaji orodha au maandishi.');
}

function _ondoa(list, item) {
  const i = list.findIndex((x) => _eq(x, item));
  if (i >= 0) list.splice(i, 1);
}

// uliza (input) is not meaningful headless. Emit a polite stub that returns "".
function _uliza(prompt) {
  // In a Node/web headless context there is no interactive stdin; SNIL's default
  // io.uliza also returns "". Returning "" keeps behaviour deterministic.
  return "";
}

// ── Global builtins (no leta): namba, maandishi, mzunguko, kamili ──
function namba(x) {
  if (typeof x === "boolean") throw new Error('Kazi "namba" inahitaji maandishi au namba.');
  if (typeof x === "number") return x;
  if (typeof x === "string") {
    const t = x.trim();
    const n = Number(t);
    if (t === "" || Number.isNaN(n)) throw new Error('Kazi "namba" haiwezi kugeuza "' + x + '" kuwa namba.');
    return n;
  }
  throw new Error('Kazi "namba" inahitaji maandishi au namba.');
}

function _maandishi(x) { return _str(x); }

function mzunguko(x) {
  if (typeof x !== "number") throw new Error('Kazi "mzunguko" inahitaji namba.');
  return Math.round(x);
}

function kamili(x) {
  if (typeof x !== "number") throw new Error('Kazi "kamili" inahitaji namba.');
  return Math.abs(x);
}

function _roundHalfUp(x, dp) {
  const f = Math.pow(10, dp);
  const r = Math.round(Math.abs(x) * f) / f;
  return x < 0 ? -r : r;
}

function _clamp(i, n) {
  if (i < 0) return 0;
  if (i > n) return n;
  return i;
}

function _numList(args, fn) {
  let raw = (args.length === 1 && Array.isArray(args[0])) ? args[0] : args;
  for (const v of raw) if (typeof v !== "number") throw new Error('Kazi "' + fn + '" inahitaji namba.');
  return raw;
}

// ── SNIL stdlib (leta hisabati / maandishi / orodha / muda / faili) ──
const hisabati = {
  jumla: (...a) => _numList(a, "jumla").reduce((x, y) => x + y, 0),
  wastani: (...a) => { const n = _numList(a, "wastani"); if (n.length === 0) throw new Error('Kazi "wastani" inahitaji angalau namba moja.'); return n.reduce((x, y) => x + y, 0) / n.length; },
  kiwango_cha_juu: (...a) => { const n = _numList(a, "kiwango_cha_juu"); if (n.length === 0) throw new Error('Kazi "kiwango_cha_juu" inahitaji angalau namba moja.'); return Math.max(...n); },
  kiwango_cha_chini: (...a) => { const n = _numList(a, "kiwango_cha_chini"); if (n.length === 0) throw new Error('Kazi "kiwango_cha_chini" inahitaji angalau namba moja.'); return Math.min(...n); },
  mzizi: (x) => { if (typeof x !== "number") throw new Error('Kazi "mzizi" inahitaji namba.'); if (x < 0) throw new Error('Kazi "mzizi" haiwezi kuchukua mzizi wa namba hasi.'); return Math.sqrt(x); },
  kipeo: (b, e) => { if (typeof b !== "number" || typeof e !== "number") throw new Error('Kazi "kipeo" inahitaji namba.'); return Math.pow(b, e); },
  kipeo_cha_pili: (x) => { if (typeof x !== "number") throw new Error('Kazi "kipeo_cha_pili" inahitaji namba.'); return x * x; },
  salio: (a, b) => { if (typeof a !== "number" || typeof b !== "number") throw new Error('Kazi "salio" inahitaji namba.'); if (b === 0) throw new Error('Kazi "salio" haiwezi kugawanya kwa sifuri.'); return a % b; },
  mviringo: (x, dp) => { if (typeof x !== "number") throw new Error('Kazi "mviringo" inahitaji namba.'); if (typeof dp !== "number" || !Number.isInteger(dp)) throw new Error('Kazi "mviringo" inahitaji namba kamili.'); if (dp < 0) throw new Error('Kazi "mviringo" inahitaji idadi ya desimali isiyo hasi.'); return _roundHalfUp(x, dp); },
  mviringo_juu: (x) => { if (typeof x !== "number") throw new Error('Kazi "mviringo_juu" inahitaji namba.'); return Math.ceil(x); },
  mviringo_chini: (x) => { if (typeof x !== "number") throw new Error('Kazi "mviringo_chini" inahitaji namba.'); return Math.floor(x); },
  thamani_kamili: (x) => { if (typeof x !== "number") throw new Error('Kazi "thamani_kamili" inahitaji namba.'); return Math.abs(x); },
};

const maandishi = {
  herufi_kubwa: (s) => String(s).toUpperCase(),
  herufi_ndogo: (s) => String(s).toLowerCase(),
  unganisha: (list, sep) => { if (!Array.isArray(list)) throw new Error('Kazi "unganisha" inahitaji orodha.'); return list.map(_str).join(sep === undefined ? "" : sep); },
  gawanya: (s, sep) => { s = String(s); if (sep === undefined || sep === "") return s.split(""); return s.split(sep); },
  ina: (s, part) => String(s).includes(String(part)),
  badilisha: (s, oldS, neu) => String(s).split(String(oldS)).join(String(neu)),
  ondoa_nafasi: (s) => String(s).trim(),
  anza_na: (s, x) => String(s).startsWith(String(x)),
  isha_na: (s, x) => String(s).endsWith(String(x)),
  pata: (s, x) => String(s).indexOf(String(x)),
  pindua: (s) => String(s).split("").reverse().join(""),
  rudia: (s, n) => { if (typeof n !== "number" || !Number.isInteger(n)) throw new Error('Kazi "rudia" inahitaji namba kamili.'); if (n < 0) throw new Error('Kazi "rudia" inahitaji idadi isiyo hasi.'); return String(s).repeat(n); },
  kata: (s, anza, mwisho) => { if (typeof anza !== "number" || !Number.isInteger(anza) || typeof mwisho !== "number" || !Number.isInteger(mwisho)) throw new Error('Kazi "kata" inahitaji namba kamili.'); s = String(s); const a = _clamp(anza, s.length), b = _clamp(mwisho, s.length); return a >= b ? "" : s.slice(a, b); },
};

const orodha = {
  panga: (list) => {
    if (!Array.isArray(list)) throw new Error('Kazi "panga" inahitaji orodha.');
    const copy = list.slice();
    const allNum = copy.every((x) => typeof x === "number");
    const allStr = copy.every((x) => typeof x === "string");
    if (!allNum && !allStr) throw new Error('Kazi "panga" inahitaji orodha ya namba pekee au maandishi pekee.');
    if (allNum) copy.sort((a, b) => a - b);
    else copy.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
    return copy;
  },
  geuza: (list) => { if (!Array.isArray(list)) throw new Error('Kazi "geuza" inahitaji orodha.'); return list.slice().reverse(); },
  ina: (list, kitu) => { if (!Array.isArray(list)) throw new Error('Kazi "ina" inahitaji orodha.'); return list.some((x) => _eq(x, kitu)); },
  chukua: (list, anza, mwisho) => { if (!Array.isArray(list)) throw new Error('Kazi "chukua" inahitaji orodha.'); if (typeof anza !== "number" || !Number.isInteger(anza) || typeof mwisho !== "number" || !Number.isInteger(mwisho)) throw new Error('Kazi "chukua" inahitaji namba kamili.'); const a = _clamp(anza, list.length), b = _clamp(mwisho, list.length); return a >= b ? [] : list.slice(a, b); },
  fahirisi: (list, kitu) => { if (!Array.isArray(list)) throw new Error('Kazi "fahirisi" inahitaji orodha.'); return list.findIndex((x) => _eq(x, kitu)); },
  unganisha_mbili: (a, b) => { if (!Array.isArray(a) || !Array.isArray(b)) throw new Error('Kazi "unganisha_mbili" inahitaji orodha.'); return a.concat(b); },
  kichwa: (list) => { if (!Array.isArray(list)) throw new Error('Kazi "kichwa" inahitaji orodha.'); if (list.length === 0) throw new Error('Kazi "kichwa" inahitaji orodha isiyo tupu.'); return list[0]; },
  mkia: (list) => { if (!Array.isArray(list)) throw new Error('Kazi "mkia" inahitaji orodha.'); if (list.length === 0) throw new Error('Kazi "mkia" inahitaji orodha isiyo tupu.'); return list.slice(1); },
};

function _isDict(d) {
  return d !== null && typeof d === "object" && !Array.isArray(d);
}

const kamusi = {
  funguo: (d) => { if (!_isDict(d)) throw new Error('Kazi "funguo" inahitaji kamusi.'); return Object.keys(d); },
  thamani: (d) => { if (!_isDict(d)) throw new Error('Kazi "thamani" inahitaji kamusi.'); return Object.keys(d).map((k) => d[k]); },
  ina_ufunguo: (d, key) => { if (!_isDict(d)) throw new Error('Kazi "ina_ufunguo" inahitaji kamusi.'); return Object.prototype.hasOwnProperty.call(d, key); },
  idadi_funguo: (d) => { if (!_isDict(d)) throw new Error('Kazi "idadi_funguo" inahitaji kamusi.'); return Object.keys(d).length; },
};

const muda = {
  sasa: () => new Date().toISOString(),
  leo: () => new Date().toISOString().slice(0, 10),
  mwaka: () => new Date().getFullYear(),
  mwezi: () => new Date().getMonth() + 1,
  siku: () => new Date().getDate(),
};

const faili = {
  soma: (path) => { const fs = require("fs"); return fs.readFileSync(String(path), "utf-8"); },
  andika: (path, data) => { const fs = require("fs"); fs.writeFileSync(String(path), _str(data === undefined ? "" : data), "utf-8"); return null; },
  ipo: (path) => { const fs = require("fs"); return fs.existsSync(String(path)); },
  futa: (path) => { const fs = require("fs"); if (fs.existsSync(String(path))) fs.unlinkSync(String(path)); return null; },
};

function _flush() { if (_out.length) console.log(_out.join("\\n")); }
`;

// Identifier names that conflict with JS keywords/reserved words/prelude globals
// are mangled. SNIL identifiers are Kiswahili but a few collide (e.g. `for`, `if`)
// or could shadow prelude helpers — mangle conservatively.
const JS_RESERVED = new Set([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default',
  'delete', 'do', 'else', 'export', 'extends', 'false', 'finally', 'for',
  'function', 'if', 'import', 'in', 'instanceof', 'new', 'null', 'return',
  'super', 'switch', 'this', 'throw', 'true', 'try', 'typeof', 'var', 'void',
  'while', 'with', 'yield', 'let', 'static', 'enum', 'await', 'async',
  'implements', 'interface', 'package', 'private', 'protected', 'public',
  'arguments', 'eval',
]);

function safeName(name: string): string {
  if (JS_RESERVED.has(name)) return name + '_';
  // Names that begin with `_` could collide with prelude helpers; SNIL user
  // identifiers cannot start with `_` per the lexer, so no extra guard needed.
  return name;
}

export function generateJS(program: Program, somaModuli?: import('./runtime').ModuleResolver): string {
  const out: string[] = [];

  function line(text: string, depth: number): void {
    out.push('  '.repeat(depth) + text);
  }

  function block(stmts: Stmt[], depth: number): void {
    for (const s of stmts) emitStmt(s, depth);
  }

  function emitStmt(s: Stmt, depth: number): void {
    switch (s.kind) {
      case 'VarDecl': {
        const n = s as VarDecl;
        // `weka` may re-declare an existing name (SNIL allows it). Use an
        // assign-or-declare pattern at top level via `var` to stay idempotent;
        // but inside functions/blocks `var` is hoisted, which is safe here too.
        line(`var ${safeName(n.name)} = ${expr(n.value)};`, depth);
        return;
      }
      case 'Assign': {
        const n = s as Assign;
        line(`${lvalue(n.target)} = ${expr(n.value)};`, depth);
        return;
      }
      case 'Print': {
        const n = s as Print;
        line(`_onyesha(${expr(n.value)});`, depth);
        return;
      }
      case 'Input': {
        const n = s as Input;
        line(`var ${safeName(n.name)} = _uliza(_str(${expr(n.prompt)}));`, depth);
        return;
      }
      case 'If': {
        const n = s as If;
        line(`if (_kweli(${expr(n.cond)})) {`, depth);
        block(n.then, depth + 1);
        if (n.otherwise !== null) {
          line('} else {', depth);
          block(n.otherwise, depth + 1);
          line('}', depth);
        } else {
          line('}', depth);
        }
        return;
      }
      case 'ForEach': {
        const n = s as ForEach;
        line(`for (const ${safeName(n.varName)} of ${expr(n.iterable)}) {`, depth);
        block(n.body, depth + 1);
        line('}', depth);
        return;
      }
      case 'ForRange': {
        const n = s as ForRange;
        // a..b INCLUSIVE both ends; step +1 up, -1 down (match interpreter).
        const v = safeName(n.varName);
        const from = `_from_${depth}_${v}`;
        const to = `_to_${depth}_${v}`;
        line(`{ const ${from} = ${expr(n.from)}, ${to} = ${expr(n.to)};`, depth);
        line(`if (${from} <= ${to}) {`, depth);
        line(`for (let ${v} = ${from}; ${v} <= ${to}; ${v}++) {`, depth + 1);
        block(n.body, depth + 2);
        line('}', depth + 1);
        line('} else {', depth);
        line(`for (let ${v} = ${from}; ${v} >= ${to}; ${v}--) {`, depth + 1);
        block(n.body, depth + 2);
        line('}', depth + 1);
        line('} }', depth);
        return;
      }
      case 'While': {
        const n = s as While;
        line(`while (_kweli(${expr(n.cond)})) {`, depth);
        block(n.body, depth + 1);
        line('}', depth);
        return;
      }
      case 'FuncDecl': {
        const n = s as FuncDecl;
        const params = n.params.map(safeName).join(', ');
        line(`function ${safeName(n.name)}(${params}) {`, depth);
        block(n.body, depth + 1);
        line('}', depth);
        return;
      }
      case 'Return': {
        const n = s as Return;
        line(n.value === null ? 'return;' : `return ${expr(n.value)};`, depth);
        return;
      }
      case 'Try': {
        const n = s as Try;
        line('try {', depth);
        block(n.body, depth + 1);
        line('} catch (_e) {', depth);
        block(n.handler, depth + 1);
        line('}', depth);
        return;
      }
      case 'Import': {
        const n = s as Import;
        if (n.isFile) {
          // File module: compiled statements are inlined ONCE at top level (see
          // gatherFileModules below), so the import site emits nothing.
          line(`// leta "${n.module}"`, depth);
          return;
        }
        // `leta X` flattens the stdlib module's functions into bare names —
        // matching the interpreter (so `jumla(...)` works after `leta hisabati`).
        const mod = STDLIB[n.module];
        if (mod) {
          for (const fn of Object.keys(mod)) line(`var ${safeName(fn)} = ${n.module}.${fn};`, depth);
        } else {
          line(`// leta ${n.module}`, depth);
        }
        return;
      }
      case 'ListAdd': {
        const n = s as ListAdd;
        line(`(${expr(n.list)}).push(${expr(n.item)});`, depth);
        return;
      }
      case 'ListRemove': {
        const n = s as ListRemove;
        line(`_ondoa(${expr(n.list)}, ${expr(n.item)});`, depth);
        return;
      }
      case 'FileWrite': {
        const n = s as FileWrite;
        line(`require("fs").writeFileSync(${expr(n.path)}, _str(${expr(n.data)}), "utf-8");`, depth);
        return;
      }
      case 'FileRead': {
        const n = s as FileRead;
        line(`var ${safeName(n.name)} = require("fs").readFileSync(${expr(n.path)}, "utf-8");`, depth);
        return;
      }
      case 'ExprStmt': {
        const n = s as ExprStmt;
        line(`${expr(n.expr)};`, depth);
        return;
      }
      default: {
        const _exhaustive: never = s;
        throw new Error(`SNIL codegen: aina ya sentensi haijatekelezwa: ${(_exhaustive as Stmt).kind}`);
      }
    }
  }

  function lvalue(target: Ident | Index | Member): string {
    switch (target.kind) {
      case 'Ident':
        return safeName(target.name);
      case 'Index':
        return `${expr(target.target)}[${expr(target.index)}]`;
      case 'Member':
        // SNIL dicts compile to JS objects → member access is subscript.
        return `${expr(target.target)}[${str(target.name)}]`;
    }
  }

  function str(s: string): string {
    return JSON.stringify(s);
  }

  function expr(e: Expr): string {
    switch (e.kind) {
      case 'NumberLit':
        return String(e.value);
      case 'StringLit':
        return str(e.value);
      case 'TemplateString': {
        // "Habari {jina}!" → ("Habari " + _str(jina) + "!"). Literal parts stay
        // plain strings; expr parts go through _str (same stringify as SNIL `+`).
        const pieces = e.parts.map((p) =>
          p.t === 'lit' ? str(p.value) : `_str(${expr(p.expr)})`,
        );
        return pieces.length ? `(${pieces.join(' + ')})` : '""';
      }
      case 'BoolLit':
        return e.value ? 'true' : 'false';
      case 'NullLit':
        return 'null';
      case 'ListLit':
        return `[${e.items.map(expr).join(', ')}]`;
      case 'DictLit':
        return `{${e.entries.map((en) => `${str(en.key)}: ${expr(en.value)}`).join(', ')}}`;
      case 'Ident':
        return safeName(e.name);
      case 'Binary':
        return binary(e as Binary);
      case 'Unary':
        return unary(e as Unary);
      case 'Call':
        return call(e as Call);
      case 'Index':
        return `${expr((e as Index).target)}[${expr((e as Index).index)}]`;
      case 'Member':
        return `${expr((e as Member).target)}[${str((e as Member).name)}]`;
      default: {
        const _exhaustive: never = e;
        throw new Error(`SNIL codegen: aina ya msemo haijatekelezwa: ${(_exhaustive as Expr).kind}`);
      }
    }
  }

  function binary(e: Binary): string {
    const l = expr(e.left);
    const r = expr(e.right);
    switch (e.op) {
      case '+':
        // SNIL `+`: string-concat if either side is text, else numeric add.
        return `_jumla(${l}, ${r})`;
      case '-': return `(${l} - ${r})`;
      case '*': return `(${l} * ${r})`;
      case '/': return `_gawanya(${l}, ${r})`;
      case '%': return `(${l} % ${r})`;
      case '==': return `_eq(${l}, ${r})`;
      case '!=': return `(!_eq(${l}, ${r}))`;
      case '<': return `(${l} < ${r})`;
      case '>': return `(${l} > ${r})`;
      case '<=': return `(${l} <= ${r})`;
      case '>=': return `(${l} >= ${r})`;
      // na/au short-circuit AND return a boolean (matches interpreter, which
      // returns isTruthy of the deciding operand). Wrap operands in _kweli.
      case 'na': return `(_kweli(${l}) ? _kweli(${r}) : false)`;
      case 'au': return `(_kweli(${l}) ? true : _kweli(${r}))`;
    }
  }

  function unary(e: Unary): string {
    const v = expr(e.operand);
    if (e.op === 'sio') return `(!_kweli(${v}))`;
    return `(-${v})`;
  }

  function call(e: Call): string {
    const args = e.args.map(expr).join(', ');
    // Global builtins available without `leta`.
    if (e.callee === 'idadi') return `_idadi(${args})`;
    // `maandishi` is BOTH a global builtin and a module name; the module object
    // shadows the builtin, so route the global display-string builtin to its
    // underscored prelude function (like _idadi). Mirrors the Python backend.
    if (e.callee === 'maandishi') return `_maandishi(${args})`;
    return `${safeName(e.callee)}(${args})`;
  }

  // ── gather transitively-imported file modules ──
  // DFS from main, DEDUPED by module name, CYCLE-SAFE (don't recurse into a
  // module already on the visiting stack), emitted in dependency order
  // (imported-before-importer). Each module body is compiled exactly ONCE so its
  // top-level kazi/weka become global names — exactly the bare-name exposure the
  // interpreter produces. Mirrors codegen_python.ts.
  function fileImportsOf(body: Stmt[]): Import[] {
    const found: Import[] = [];
    for (const s of body) {
      if (s.kind === 'Import' && (s as Import).isFile) found.push(s as Import);
    }
    return found;
  }

  const moduleOrder: { name: string; body: Stmt[] }[] = [];
  const emitted = new Set<string>();
  const visiting = new Set<string>();

  function visitModule(imp: Import): void {
    const name = imp.module;
    if (emitted.has(name)) return;
    if (visiting.has(name)) return;
    if (!somaModuli) {
      throw new SnilError(
        `Moduli "${name}" haijapatikana.`, imp.line, 'kutekeleza',
        'mazingira haya hayana kisuluhishi cha moduli (somaModuli)',
      );
    }
    const source = somaModuli(name);
    if (source == null) {
      throw new SnilError(`Moduli "${name}" haijapatikana.`, imp.line, 'kutekeleza');
    }
    const modProgram = parseTokens(tokenize(source));
    visiting.add(name);
    for (const dep of fileImportsOf(modProgram.body)) visitModule(dep);
    visiting.delete(name);
    if (!emitted.has(name)) {
      emitted.add(name);
      moduleOrder.push({ name, body: modProgram.body });
    }
  }

  for (const imp of fileImportsOf(program.body)) visitModule(imp);

  // ── assemble ──
  // 1) inlined file-modules (dependency order), each emitted ONCE at top level.
  for (const mod of moduleOrder) {
    out.push(`// ── moduli "${mod.name}" (imeingizwa moja kwa moja) ──`);
    for (const s of mod.body) emitStmt(s, 0);
  }
  // 2) the main program body.
  for (const s of program.body) emitStmt(s, 0);
  // 3) flush collected output once at the end.
  out.push('_flush();');

  return PRELUDE + '\n' + out.join('\n') + '\n';
}
